/* 
 _____  _               _____ _____ _____  _    _  _____           __   __
|  __ \| |        /\   / ____|_   _|  __ \| |  | |/ ____|    /\    \ \ / /
| |__) | |       /  \ | |      | | | |  | | |  | | (___     /  \    \ V / 
|  ___/| |      / /\ \| |      | | | |  | | |  | |\___ \   / /\ \    > <  
| |    | |____ / ____ \ |____ _| |_| |__| | |__| |____) | / ____ \  / . \ 
|_|    |______/_/    \_\_____|_____|_____/ \____/|_____/ /_/    \_\/_/ \_\

 2026 FRC Team 8817 - Buccaneer Robotics
*/
package frc.robot;

import static edu.wpi.first.units.Units.*;
import org.littletonrobotics.junction.Logger;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.button.RobotModeTriggers;
import frc.robot.subsystems.indexer.IndexerSubsystem;
import frc.robot.subsystems.intake.IntakeSubsystem;
import frc.robot.subsystems.intakepivot.IntakePivotSubsystem;
import frc.robot.subsystems.shooter.ShooterSubsystem;
import frc.robot.subsystems.vision.Vision;
import frc.robot.commands.ShootOnMoveCommand;
import frc.robot.commands.autos.*;
import frc.robot.generated.TunerConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;

/**
 * The "brain" of robot setup:
 *   1) Creates every subsystem
 *   2) Maps every controller button to an action
 *   3) Builds autonomous routines and adds them to a Shuffleboard dropdown
 */
public class RobotContainer {

    // ===== Subsystems (one per physical mechanism) =====
    public final Vision vision = new Vision();
    public final ShooterSubsystem shooter = new ShooterSubsystem();
    public final IntakePivotSubsystem intakePivot = new IntakePivotSubsystem();
    public final IntakeSubsystem intake = new IntakeSubsystem();
    public final IndexerSubsystem indexer = new IndexerSubsystem();

    // Auto chooser dropdown on Shuffleboard
    private final SendableChooser<Command> autoChooser = new SendableChooser<>();

    // Max translation speed (m/s) and rotation speed (rad/s)
    private double MaxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
    private double MaxAngularRate = RotationsPerSecond.of(1.5).in(RadiansPerSecond);

    // Field-centric drive request reused every loop cycle.
    // "Push stick forward = robot drives away from driver wall" regardless of heading.
    private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
            .withDeadband(MaxSpeed * 0.1)
            .withRotationalDeadband(MaxAngularRate * 0.1)
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

    private final Telemetry logger = new Telemetry(MaxSpeed);

    // Controllers: port 0 = driver, port 1 = operator
    private final CommandXboxController driver = new CommandXboxController(0);
    private final CommandXboxController operator = new CommandXboxController(1);

    // Swerve drivetrain (generated by CTRE Tuner X)
    public final CommandSwerveDrivetrain drivetrain = TunerConstants.createDrivetrain();
    

    public RobotContainer() {
        drivetrain.configurePathPlanner();
        drivetrain.configureOrchestra();
        configureAutoChooser();
        configureBindings(); 
    }

    /** Register all auto routines in the Shuffleboard dropdown. */
    private void configureAutoChooser() {
        autoChooser.addOption("Drive Straight", DriveStraight.build(drivetrain));
        autoChooser.addOption("Outpost Single Swipe",
            OutpostSingleSwipe.build(drivetrain, shooter, indexer, intake, intakePivot, vision, MaxAngularRate));
        autoChooser.addOption("Outpost Double Swipe",
            OutpostDoubleSwipe.build(drivetrain, shooter, indexer, intake, intakePivot, vision, MaxAngularRate));
        autoChooser.addOption("Depot Single",
            DepotSingleSwipe.build(drivetrain, shooter, indexer, intake, intakePivot, vision, MaxAngularRate));
        autoChooser.addOption("Hub",
            Hub.build(drivetrain, shooter, indexer, intake, intakePivot, vision, MaxAngularRate));

        ShuffleboardTab autoTab = Shuffleboard.getTab("Autonomous");
        autoTab.add(autoChooser);
    }

    /**
     * Wire every button to an action. See inline comments for the full mapping.
     *
     * DRIVER: left stick = translate, right stick = rotate, bumpers/triggers = shoot/intake
     * OPERATOR: redundant intake controls + manual shot tuning via d-pad
     */
    private void configureBindings() {
        // Default command: always reads joysticks and drives the robot
        drivetrain.setDefaultCommand(
            drivetrain.applyRequest(() ->
                drive.withVelocityX(driver.getLeftY() * MaxSpeed)
                    .withVelocityY(driver.getLeftX() * MaxSpeed)
                    .withRotationalRate(-driver.getRightX() * MaxAngularRate)));

        // Idle modules when disabled so they don't overheat holding position
        final var idle = new SwerveRequest.Idle();
        RobotModeTriggers.disabled().whileTrue(
            drivetrain.applyRequest(() -> idle).ignoringDisable(true));

        // Right stick click = reset field-centric heading
        driver.rightStick().onTrue(drivetrain.runOnce(drivetrain::seedFieldCentric));
        drivetrain.registerTelemetry(logger::telemeterize);

        // --- DRIVER: Shooter ---
        // Right bumper (hold) = spin up flywheels
        driver.rightBumper()
            .onTrue(new InstantCommand(() -> shooter.setWantedState(ShooterSubsystem.WantedState.PREPARE_SHOT)))
            .onFalse(new InstantCommand(() -> shooter.setWantedState(ShooterSubsystem.WantedState.IDLE)));

        // Right trigger (hold) = full shoot-on-move (auto-aim + spin + feed while driving)
        driver.rightTrigger().whileTrue(
            new ShootOnMoveCommand(drivetrain, shooter, vision, indexer, intakePivot,
                () -> driver.getLeftY(), () -> driver.getLeftX(), () -> -driver.getRightX(),
                MaxSpeed, MaxAngularRate));

        // --- DRIVER: Intake ---
        driver.leftTrigger()
            .whileTrue(Commands.runOnce(() -> intake.setWantedState(IntakeSubsystem.WantedState.INTAKE)))
            .whileFalse(Commands.runOnce(() -> intake.setWantedState(IntakeSubsystem.WantedState.IDLE)));
        driver.povDown()
            .whileTrue(Commands.runOnce(() -> intake.setWantedState(IntakeSubsystem.WantedState.SPIT)))
            .whileFalse(Commands.runOnce(() -> intake.setWantedState(IntakeSubsystem.WantedState.IDLE)));
        driver.leftBumper().onTrue(new InstantCommand(() -> {
            shooter.setFeedEnabled(true);
            shooter.setWantedState(ShooterSubsystem.WantedState.MANUAL_SHOT);
        }));
        driver.leftBumper().onFalse(new InstantCommand(() -> {
            shooter.setFeedEnabled(false);
            if (operator.rightBumper().getAsBoolean()) {
                shooter.setWantedState(ShooterSubsystem.WantedState.PREPARE_SHOT);
            } else {
                shooter.setWantedState(ShooterSubsystem.WantedState.IDLE);
            }
        }));

        // --- DRIVER: Pivot + Indexer ---
        driver.a()
            .whileTrue(Commands.runOnce(() -> intakePivot.setWantedState(IntakePivotSubsystem.WantedState.DEPLOY)))
            .whileFalse(Commands.runOnce(() -> intakePivot.setWantedState(IntakePivotSubsystem.WantedState.IDLE)));
        driver.b()
            .whileTrue(Commands.runOnce(() -> intakePivot.setWantedState(IntakePivotSubsystem.WantedState.STOW)))
            .whileFalse(Commands.runOnce(() -> intakePivot.setWantedState(IntakePivotSubsystem.WantedState.IDLE)));
        driver.x()
            .whileTrue(Commands.runOnce(() -> indexer.setWantedState(IndexerSubsystem.WantedState.INDEX)))
            .whileFalse(Commands.runOnce(() -> indexer.setWantedState(IndexerSubsystem.WantedState.IDLE)));

        driver.y().onTrue(Commands.runOnce(drivetrain::playMusic));
        driver.povRight().onTrue(Commands.runOnce(drivetrain::stopMusic));

        // --- OPERATOR: Redundant intake/pivot/indexer ---
        operator.y()
            .whileTrue(Commands.runOnce(() -> intakePivot.setWantedState(IntakePivotSubsystem.WantedState.DEPLOY)))
            .whileFalse(Commands.runOnce(() -> intakePivot.setWantedState(IntakePivotSubsystem.WantedState.IDLE)));
        operator.a()
            .whileTrue(Commands.runOnce(() -> intakePivot.setWantedState(IntakePivotSubsystem.WantedState.STOW)))
            .whileFalse(Commands.runOnce(() -> intakePivot.setWantedState(IntakePivotSubsystem.WantedState.IDLE)));
        operator.x()
            .whileTrue(Commands.runOnce(() -> indexer.setWantedState(IndexerSubsystem.WantedState.INDEX)))
            .whileFalse(Commands.runOnce(() -> indexer.setWantedState(IndexerSubsystem.WantedState.IDLE)));
        operator.leftTrigger()
            .whileTrue(Commands.runOnce(() -> intake.setWantedState(IntakeSubsystem.WantedState.SPIT)))
            .whileFalse(Commands.runOnce(() -> intake.setWantedState(IntakeSubsystem.WantedState.IDLE)));
        operator.rightTrigger()
            .whileTrue(Commands.runOnce(() -> intake.setWantedState(IntakeSubsystem.WantedState.INTAKE)))
            .whileFalse(Commands.runOnce(() -> intake.setWantedState(IntakeSubsystem.WantedState.IDLE)));

        // --- OPERATOR: Manual shot tuning ---
        // Back = snapshot current auto-aim values into manual fallback
        operator.back().onTrue(new InstantCommand(() -> shooter.syncManualToCurrentTargets()));
        // D-pad = tweak hood angle and shooter speed
        operator.povUp().whileTrue(Commands.run(() -> shooter.adjustManualHood(+0.01)));
        operator.povDown().whileTrue(Commands.run(() -> shooter.adjustManualHood(-0.01)));
        operator.povRight().onTrue(new InstantCommand(() -> shooter.adjustManualShooterRps(+1.0)));
        operator.povLeft().onTrue(new InstantCommand(() -> shooter.adjustManualShooterRps(-1.0)));

        // RB = table-based shot prep, LB = manual fallback shot
        operator.rightBumper().onTrue(new InstantCommand(() -> {
            shooter.setFeedEnabled(false);
            shooter.setWantedState(ShooterSubsystem.WantedState.PREPARE_SHOT);
        }));
        operator.rightBumper().onFalse(new InstantCommand(() -> {
            if (operator.leftBumper().getAsBoolean()) {
                shooter.setFeedEnabled(true);
                shooter.setWantedState(ShooterSubsystem.WantedState.MANUAL_SHOT);
            } else {
                shooter.setFeedEnabled(false);
                shooter.setWantedState(ShooterSubsystem.WantedState.IDLE);
            }
        }));
        operator.leftBumper().onTrue(new InstantCommand(() -> {
            shooter.setFeedEnabled(true);
            shooter.setWantedState(ShooterSubsystem.WantedState.MANUAL_SHOT);
        }));
        operator.leftBumper().onFalse(new InstantCommand(() -> {
            shooter.setFeedEnabled(false);
            if (operator.rightBumper().getAsBoolean()) {
                shooter.setWantedState(ShooterSubsystem.WantedState.PREPARE_SHOT);
            } else {
                shooter.setWantedState(ShooterSubsystem.WantedState.IDLE);
            }
        }));
    }

    /** Called every 20ms - feeds vision pose measurements into the drivetrain estimator. */
    public void periodic() {
        Logger.recordOutput("AutoDebug/Test", true);
        vision.updateVisionPose(drivetrain);
    }

    /** Returns whichever auto was selected on Shuffleboard. */
    public Command getAutonomousCommand() {
        return autoChooser.getSelected();
    }
}
